/*
 * generated by Xtext 2.24.0
 */
package com.regnosys.rosetta.validation

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class RosettaValidator extends AbstractRosettaValidator {

	
}
