/*
 * generated by Xtext 2.24.0
 */
package com.regnosys.rosetta

import com.regnosys.rosetta.formatting2.RosettaExpressionFormatter

/* Use this class to register components to be used at runtime / without the Equinox extension registry.*/
class RosettaRuntimeModule extends AbstractRosettaRuntimeModule {
	

	def Class<? extends RosettaExpressionFormatter> bindRosettaExpressionFormatter() {
		RosettaExpressionFormatter
	}
}
