/*
 * generated by Xtext 2.24.0
 */
package com.regnosys.rosetta


/* Use this class to register components to be used at runtime / without the Equinox extension registry.*/
class RosettaRuntimeModule extends AbstractRosettaRuntimeModule {

}
