grammar com.regnosys.rosetta.Rosetta with org.eclipse.xtext.common.Terminals
import "http://www.rosetta-model.com/RosettaExpression"


Expression returns RosettaExpression:
	ExistsExpression
;

ExistsExpression returns RosettaExpression:
	RosettaBooleanLiteral
	(
		=>(
			({RosettaExistsExpression.argument=current} 'exists')
			
		)
	)*
;

RosettaBooleanLiteral:
	value?='True' | {RosettaBooleanLiteral} 'False'
;


