/*
 * Copyright (c) REGnosys 2018 (www.regnosys.com) 
 * generated by Xtext 2.27.0
 */
package com.regnosys.rosetta.ide


/**
 * Use this class to register ide components.
 */
class RosettaIdeModule extends AbstractRosettaIdeModule {
}
